// Regenerates static/mock-data.js from data/ so mock mode uses the same taxonomy and presets as the backend.
//   node scripts/build_mock_data.mjs
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), "utf8"));

// Keyword hints the mock uses to fake plausible answers. Keys are "query|sub_query|heading".
const leafKeywords = {
  "Warranty|Air conditioning|My AC is not cooling or cooling less": ["not cooling", "stopped cooling", "cooling less", "ac not"],
  "Warranty|Air conditioning|Foul smell coming from AC": ["smell", "odour", "odor"],
  "Warranty|Air conditioning|Noise from AC": ["ac noise", "noise from ac"],
  "Warranty|Suspension and Steering|Noise from suspension": ["suspension", "speed breaker", "bump"],
  "Warranty|Noise|Suspension": ["knocking noise"],
  "Warranty|Unable to start Car or Battery|Car is not starting": ["start nahi", "won't start", "not starting", "doesn't start"],
  "Warranty|Unable to start Car or Battery|Battery warning light is ON": ["battery wali light", "battery light", "battery warning"],
  "Warranty|Unable to start Car or Battery|Battery is discharged": ["battery dead", "battery discharged"],
  "Warranty|Engine and Transmission|Engine light is ON": ["engine light", "check engine"],
  "Warranty|Engine and Transmission|Engine is overheating": ["overheat", "temperature"],
  "Warranty|Mileage or Pickup|My car has low pickup": ["pickup", "weak on", "uphill"],
  "Warranty|Mileage or Pickup|Less mileage": ["mileage"],
  "Warranty|Brake|Hard braking": ["brakes hard", "hard braking"],
  "Warranty|Gear or Clutch|Hard to shift the gears": ["gear shift", "gears are hard"],
  "Warranty|Keys or Locks|Central locking is not working": ["central locking"],
  "Warranty|Standard Fitment and Features|Infotainment system issues": ["infotainment", "music system", "screen"],
  "Warranty|Wheels and Tyres|Damaged or defective tyre": ["tyre", "puncture"],
  "RC|RC Status|RC transfer is taking too long": ["previous owner", "rc transfer", "rc still"],
  "RC|RTO Receipt|RTO receipt not received": ["rto receipt"],
  "Post Return|Refund not received|": ["returned the car", "refund"],
  "Fastag|Blacklisted fastag|": ["blacklisted"],
  "Fastag|New fastag not received|": ["fastag not received"],
  "Insurance|Claim|Need to register new claim": ["register a claim", "claim with the insurer", "raise a claim"],
  "Insurance|Insurance renewal|": ["renew", "renewal"],
  "Seller-Miscellaneous|Challan|Challan notice received post handover": ["handover", "sold my car"],
  "Miscellaneous|Challan|Need assistance with online challan": ["online challan", "challan"],
  "Miscellaneous|Need secondary key|": ["spare key", "second key", "secondary key"],
  "Payments|Excess amount charged|Upload cancelled cheque": ["charged extra", "excess amount"],
  "Document|Car delivery note|": ["delivery note"],
  "Document|Need B2B/B2C invoice|": ["invoice"],
  "Buyer Benefits|Initiate 5 day money back|": ["money back", "return the car"],
  "HSRP|Received a damaged registration number plate|": ["number plate"],
};

const data = { taxonomy: read("data/taxonomy.json"), presets: read("data/presets.json"), leafKeywords };
const out = `// GENERATED by scripts/build_mock_data.mjs from data/. Used only in mock mode; the live backend serves /api/config.
window.MOCK_DATA = ${JSON.stringify(data, null, 2)};
`;
writeFileSync(new URL("static/mock-data.js", root), out);
console.log("wrote static/mock-data.js");
